### ISSUE TITLE
Yaml sequence formatting

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#1198]
Currently used `eo-yaml` requires not convenient formatting of yaml sequence:
```yaml
some_sequence:
  -
    key1: value1
    key2: value2
  -
    key3: velue3
```
when sequence items are placed differently (without line break after `-`), the sequence is parsed incorrectly.

Let's use another yaml reader or update `eo-yaml`.
