### ISSUE TITLE
Provide repository content filter

### ISSUE THREAD

**Issue by andpopov** [artipie/artipie#1254]
Repository configuration should provide ability to filter content of repository by providing two lists:
1. ```include``` - list of permitted paths
2. ```exclude``` - list of forbidden paths

Where paths should support syntax of globbing or regular expressions.

* Example of repository filter with globbing syntax:
```
repo:
  type: maven
  
  filter:
	syntax: glob # glob or regexp, default is glob
	include:
		- **/*
		- log4j/log4j/2.1[7-9].*/log4j-2.1[7-9].*.{jar,pom}
		- log4j/log4j/2.2[0-9].*/log4j-2.2[0-9].*.jar
		- org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar
		- com/acme/**
	exclude:
		- log4j/log4j/[0-2].*.*/log4j-[0-2].*.*.jar
		- org/postgresql/**/*.jar
		- com/acme/exp-project/**

```

* Example of repository filter with regexp syntax:
```
repo:
  type: maven
  
  filter:
	syntax: regexp
	include:
		- org/springframework/spring-dao/1.1.3/spring-dao-1.1.3.jar
	exclude:
		- org/spring.*?/spring-d[\w]{2}/[^/]*/.*.jar
```
