### ISSUE TITLE
pypi-proxy does not work

### ISSUE THREAD

**Issue by nyxi** [artipie/artipie#1258]
```
[main] INFO com.artipie.VertxMain - Used version of Artipie: v0.28.2
```

```yaml
meta:
  base_url: https://<myhost>/
  configs: repo
  credentials:
    - type: env
  layout: flat
  storage:
    type: fs
    path: /repoconfigs
```

```yaml
repo:
  type: pypi-proxy
  remotes:
    - url: https://pypi.org/simple/
      cache:
        storage:
          type: fs
          path: /fsrepos/pypi
  permissions:
    "*":
      - "*"
```

GET `https://<myhost>/api/v1/repository/pypi`

```json
{
  "repo": {
    "type": "pypi-proxy",
    "remotes": [
      {
        "url": "https://pypi.org/simple/",
        "cache": {
          "storage": {
            "type": "fs",
            "path": "/fsrepos/pypi"
          }
        }
      }
    ],
    "permissions": {
      "*": [
        "*"
      ]
    }
  }
}
```

```shell
$ ./bin/pip3 install --index-url https://<myhost>/pypi requests
Looking in indexes: https://<myhost>/pypi
ERROR: Could not find a version that satisfies the requirement requests (from versions: none)
ERROR: No matching distribution found for requests
```

```
[vert.x-eventloop-thread-0] INFO com.artipie.http.MainSlice - >> GET /pypi/requests/ HTTP_1_1

Host: <myhost>
X-Request-ID: d43b412b61a1a92f96118fbb06064688
X-Real-IP: 10.233.116.0
X-Forwarded-For: 10.233.116.0
X-Forwarded-Host: <myhost>
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Scheme: https
User-Agent: pip/22.0.2 {"ci":null,"cpu":"x86_64","distro":{"id":"jammy","libc":{"lib":"glibc","version":"2.35"},"name":"Ubuntu","version":"22.04"},"implementation":{"name":"CPython","version":"3.10.6"},"installer":{"name":"pip","version":"22.0.2"},"openssl_version":"OpenSSL 3.0.2 15 Mar 2022","python":"3.10.6","setuptools_version":"59.6.0","system":{"name":"Linux","release":"5.15.0-67-generic"}}
Accept-Encoding: gzip, deflate
Accept: text/html
Cache-Control: max-age=0
Mar 17, 2023 12:56:26 PM com.artipie.asto.LoggingStorage log
INFO: Exists 'pypi/requests': false
[Thread-74] INFO com.artipie.http.MainSlice - << NOT_FOUND
```
