### ISSUE TITLE
Error on pushing docker images to registry

### ISSUE THREAD

**Issue by EvgenyAfanasev** [artipie/artipie#1310]
I installed artipie using official docker compose file with adding volumes to host:

```yml
version: "3.3"
services:
  artipie:
    image: artipie/artipie:latest
    container_name: artipie
    restart: unless-stopped
    networks:
      - artipie-net
    ports:
      - "8081:8080"
      - "8086:8086"
    volumes:
      - /etc/artipie:/etc/artipie
      - /var/artipie/repo:/var/artipie/repo
      - /var/artipie/security:/var/artipie/security
      - artipie-data:/var/artipie/data
  front:
    image: artipie/front:latest
    container_name: front
    restart: unless-stopped
    networks:
      - artipie-net
    environment:
      - ARTIPIE_REST=http://artipie:8086
    ports:
      - "8080:8080"

volumes:
  artipie-data:

networks:
  artipie-net:
    driver: bridge
```

my /etc/artipie/artipie.yml:

```yml
meta:
  storage:
    type: fs
    path: /var/artipie/repo
  layout: flat
  credentials:
    - type: artipie
  policy:
    type: artipie
    storage:
      type: fs
      path: /var/artipie/security
```

and docker repo using /var/artipie/repo/platform.yml config:

```yml
repo:
  type: docker
  storage:
    type: fs
    path: /var/artipie/data
  permissions:
    admin:
      - upload
      - download
    "*":
      - download
```

When I tried upload my image to artipie docker registry I saw error in logs:

[vert.x-eventloop-thread-0] INFO com.artipie.http.MainSlice - >> POST /v2/platform/knowledge-api/blobs/uploads/ HTTP_1_1
Host: docker.codemagic.space
User-Agent: docker/24.0 go/go1.20.7 git-commit/HEAD kernel/5.15.90.1-microsoft-standard-WSL2 os/linux arch/amd64 containerd-client/1.6.22+unknown storage-driver/stargz UpstreamClient(Docker-Client/24.0.5 \(windows\))
Accept-Encoding: gzip
Authorization: ***
X-Forwarded-For: ***
X-Forwarded-Host: ***
X-Forwarded-Proto: https
content-length: 0

[ForkJoinPool.commonPool-worker-3] INFO com.artipie.settings.cache.CachedUsers - Successfully authenticated 'admin' user via CachedUsers(size=1),origin=AuthFromStorage
[ForkJoinPool.commonPool-worker-2] INFO com.artipie.http.MainSlice - Failure: java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.io.IOException: java.util.concurrent.CompletionException: java.nio.file.NoSuchFileException: /var/artipie/data/platform/docker/registry/v2/repositories/knowledge-api/_uploads/93666102-4f16-4348-b1c5-1c8c031e5583/started.3bb0929f-ffda-4b1f-aa4a-07f8883a903b.tmp
      at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
      at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
      at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:936)
      at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
      at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
 Caused by: com.artipie.asto.ArtipieIOException: java.io.IOException: java.util.concurrent.CompletionException: java.nio.file.NoSuchFileException: /var/artipie/data/platform/docker/registry/v2/repositories/knowledge-api/_uploads/93666102-4f16-4348-b1c5-1c8c031e5583/started.3bb0929f-ffda-4b1f-aa4a-07f8883a903b.tmp
      at com.artipie.asto.fs.FileStorage.lambda$null$7(FileStorage.java:156)
      at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
      ... 7 more
 Caused by: java.io.IOException: java.util.concurrent.CompletionException: java.nio.file.NoSuchFileException: /var/artipie/data/platform/docker/registry/v2/repositories/knowledge-api/_uploads/93666102-4f16-4348-b1c5-1c8c031e5583/started.3bb0929f-ffda-4b1f-aa4a-07f8883a903b.tmp
      at com.artipie.asto.ArtipieIOException.unwrap(ArtipieIOException.java:74)
      at com.artipie.asto.ArtipieIOException.<init>(ArtipieIOException.java:42)
     ... 9 more
 Caused by: java.util.concurrent.CompletionException: java.nio.file.NoSuchFileException: /var/artipie/data/platform/docker/registry/v2/repositories/knowledge-api/_uploads/93666102-4f16-4348-b1c5-1c8c031e5583/started.3bb0929f-ffda-4b1f-aa4a-07f8883a903b.tmp
     at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
     at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
     at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1141)
     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
     at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
     at org.cqfn.rio.channel.WritableChannelSubscriber.onSubscribe(WritableChannelSubscriber.java:110)
     at io.reactivex.internal.subscribers.StrictSubscriber.onSubscribe(StrictSubscriber.java:85)
     at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
     at io.reactivex.Flowable.subscribe(Flowable.java:14918)
     at io.reactivex.Flowable.subscribe(Flowable.java:14868)
     at com.artipie.asto.Content$From.subscribe(Content.java:112)
     at com.artipie.asto.OneTimePublisher.subscribe(OneTimePublisher.java:43)
    at org.cqfn.rio.channel.WritableChannelSubscriber.lambda$acceptAsync$0(WritableChannelSubscriber.java:90)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.NoSuchFileException: /var/artipie/data/platform/docker/registry/v2/repositories/knowledge-api/_uploads/93666102-4f16-4348-b1c5-1c8c031e5583/started.3bb0929f-ffda-4b1f-aa4a-07f8883a903b.tmp
    at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181)
    at java.base/java.nio.channels.FileChannel.open(FileChannel.java:298)
    at java.base/java.nio.channels.FileChannel.open(FileChannel.java:357)
    at org.cqfn.rio.file.File.lambda$write$1(File.java:117)
    at org.cqfn.rio.channel.WritableChannelSubscriber.onSubscribe(WritableChannelSubscriber.java:107)
    ... 12 more

**Comment by dgarus** [comment]
@EvgenyAfanasev 
Hi!
You used the wrong security config.
We rebuilt our security model, so now you should define repo permissions another way.

1. You should add to the`/var/artipie/security` directory a subfolder `users` and create a file, for example, `admin.yml`.
<img width="199" alt="image" src="https://github.com/artipie/artipie/assets/25565200/840d8591-e072-4c8d-9237-067469c4e408">

`admin.yml` can contain the following:
```yaml
# user auth info for credentials type `artipie`
type: plain # plain and sha256 types are supported
pass: 12345

# policy info
enabled: true # optional default true
permissions:
  docker_repository_permissions: # permission type
    platform: # repository name
      "*": # resource/image name, * - any image
      - * # actions list - any action is allowed
```

2. `platform.yml`. You may delete the `permissions` section, it фдкуфвн isn't in action.
```yaml
repo:
  type: docker
  storage:
    type: fs
    path: /var/artipie/data
```
As you can notice, `admin.xml` defines a user with the login `admin` and the password '12345'.
That is all you need to upload an image.
More info about credentials and security policy is [here] (https://github.com/artipie/artipie/wiki/Configuration-Policy)
