### ISSUE TITLE
Obtain roles from keycloak

### ISSUE THREAD

**Issue by SophiaHadash** [artipie/artipie#1325]
I am deploying artipie in my cluster and I'm using Keycloak authentication. Everything works as expected.

I created these files:

/var/artipie/security/roles/default/keycloak.yml
purpose: default read-only role. works as expected
```
enabled: true
    permissions:
      adapter_basic_permissions:
        "*": # any repository
          - read
      docker_repository_permissions:
        "*": # any repository
          "*": # any image/tag
            - pull
      docker_registry_permissions:
        "*": # any repository
          - base
          - catalog
      api_storage_alias_permissions:
        - read
      api_repository_permissions:
        - read
      api_role_permissions:
        - read
      api_user_permissions:
        - read
```

/var/artipie/security/roles/admin.yml
purpose: admin-role for subset of users. these users have realm-role admin in Keycloak
```
enabled: true
    permissions:
      all_permission: {}
```

/var/artipie/repo/docker.yml
purpose: enable docker repo to test push
```
repo:
      type: docker
      port: 9000
      storage:
        type: fs
        path: /var/artipie/data/docker
```

SCENARIO:
I login with a Keycloak admin user containing the realm role admin:
docker login ...

I try to push an image.

EXPECTED: I can push to the docker registry because my keycloak user has the realm role 'admin'

RESULTS: 
access denied, user has no push permissions

In the logs I see this error:
[vert.x-eventloop-thread-1] ERROR com.artipie.asto.ValueNotFoundException - Failed to read or parse file 'users/my-admin-user'

In the wiki I don't see any mention of using keycloak roles for permissions, but in one of the test cases I do see you set a realm role and client role for testing (so I'm assuming based on this that there is support for this)

Could you let me know if roles from Keycloak are supposed to work? Or is this a feature that it not present? And if so, is this on the roadmap?
