### ISSUE TITLE
Priority of remote docker repositories

### ISSUE THREAD

**Issue by dgarus** [artipie/artipie#1411]
We should have the ability to prioritize remote docker repositories.
Docker-proxy tries to upload an image from a remote repo with the highest priority `P1`. 
If the repo doesn't have the image, then docker-proxy tries to upload the image from a remote repo with a priority less than `P1` but higher than other repos have, and so on.
A priority is defined by the field `priority`.
```
  remotes:
    - url: http://localhost:8080 # the priority is 0 by default
    - url: registry-1.docker.io
      priority: 100 # this remote with the highest priority, it will be asked for an image in the first order
    - url: mcr.microsoft.com # the priority is 0 by default
```
By default, all remotes have the same priority `0`.
A priority value can be negative.
