### ISSUE TITLE
artipie users credentials using .yaml doesn't work

### ISSUE THREAD

**Issue by Tzahif** [artipie/artipie#1442]
Hi,

i am trying to use artipie type credentials but it doesn't work - only the env type is working.
i tried to do a docker login and other things and got always 401 status code.

artipie.yml - option 1
```
meta:
  storage:
    type: fs
    path: /var/artipie/repo
  credentials:
    - type: artipie
  policy:
    type: artipie
    storage:
      type: fs
      path: /var/artipie/security
```

artipie.yml - option 2
```
meta:
  storage:
    type: fs
    path: /var/artipie/repo
  credentials:
    - type: artipie
      storage:
        type: fs
        path: /var/artipie/security
```

/var/artipie/security/users/admin.yaml
```
type: plain
pass: my-password
roles:
  - api-admin
  - reader
  - writer
  ```

i also tried `path: /var/artipie/security/users`

i would appreciate help with understanding if i am doing something wrong.
also suggestion - maybe on startup adding prints of the users enabled by files credentials

**Comment by dgarus** [comment]
You should define permissions or have roles files as it is described here
https://github.com/artipie/artipie/wiki/Configuration-Policy

**Comment by dgarus** [comment]
What do you try to do?

**Comment by Tzahif** [comment]
Docker login, push, pull 
Apt install 
Rpm install

All these actions with the users credentials in the yaml files

**Comment by dgarus** [comment]
Can you study this example?

https://github.com/artipie/artipie/blob/master/artipie-main/src/test/java/com/artipie/docker/DockerLocalITCase.java

**Comment by Tzahif** [comment]
Can you give usage example with the yaml files I mentioned above, using command line, so I will understand what I did wrong?

**Comment by dgarus** [comment]
```
type: plain
pass: 123
permissions:
  adapter_basic_permissions:
    my-maven:
      - "*"
    my-npm:
      - "*"
    my-gem:
      - "*"
    my-gem-port:
      - "*"
  docker_repository_permissions:
    "*":
      "*":
        - *
  docker_registry_permissions:
    "*":
      - base
```

**Comment by Tzahif** [comment]
@dgarus this is my configs, am i doing something wrong?

/var/artipie/security/users/admin.yaml
```type: plain
pass: my-password
roles:
  - api-admin
  - reader
  - writer
```

/var/artipie/security/roles/api-admin.yaml
```
permissions:
  api_storage_alias_permissions:
    - *
  api_repository_permissions:
    - *
  api_role_permissions:
    - *
  api_user_permissions:
    - *
```

/var/artipie/security/roles/writer.yaml
```
permissions:
  adapter_basic_permissions:
    "*":
      - write
  docker_repository_permissions:
    "*":
      "*":
        - push
```

/var/artipie/security/roles/reader.yaml
```
permissions:
  adapter_basic_permissions:
    "*":
      - read
  docker_repository_permissions:
    "*":
      "*":
        - pull
```
