### ISSUE TITLE
Unable to push to docker repo using DigitalOcean Spaces (S3-compatible)

### ISSUE THREAD

**Issue by lukezbihlyj** [artipie/artipie#1456]
Unable to `docker push` to a `docker` repository backed by DigitalOcean Spaces storage (S3-compatible), fails with an error `Digest is not yet calculated`.

Uploading to a `file` repository type works perfectly fine using the same S3 storage configuration. Uploading to a `debian` repository also seems to work correctly as well. Swapping the `docker` repository to use local filesystem storage makes it work correctly, so it is specifically an issue only with the `docker repo type + s3 storage layer` combination.

One strange thing I noticed is that some of the image layer uploads do succeed, but others fail. This behaviour is consistent - the same two layers always succeed, the other two always fail. When I empty the storage bucket and try the upload again I see the exact same behaviour every time, with the same two layers succeding.

Seems like potentially a similar issue to this previously reported issue: #1369 - the only thing I noticed that is different in configuration in this issue is they're using `layout: flat` in the repository config which I tried adding but that didn't change anything.

**I created a repo with simple code to run an environment that replicates the issue: https://github.com/lukezbihlyj/artipie-docker-s3-repro**

## Tried Versions

- v0.30.15
- v0.30.14
- v1.17.16

## Setup

- Using Ubuntu 22.04
- Running artipie as a systemd service
- Running nginx as an reverse proxy for SSL

`/var/artipie/security/users/jenkins.yaml`

```
type: plain
pass: [REDACTED]
enabled: true
permissions:
  all_permission: {}
```

`/var/artipie/repo/_storages.yaml`

```
storages:
  default:
    type: s3
    endpoint: https://nyc3.digitaloceanspaces.com
    region: nyc3
    bucket: [REDACTED]
    credentials:
      type: basic
      accessKeyId: [REDACTED]
      secretAccessKey: [REDACTED]
```

`/var/artipie/repo/docker.yaml`

```
repo:
  type: docker
  port: 8083
  storage: default
```

`/etc/artipie/artipie.yaml`

```
meta:
  base_url: https://artipie.service.consul
  storage:
    type: fs
    path: /var/artipie/repo
  credentials:
    - type: artipie
  policy:
    type: artipie
    storage:
      type: fs
      path: /var/artipie/security
```

`/etc/nginx/conf.d/docker.conf`

```
upstream backend-docker {
  server localhost:8083;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name docker.artipie.service.consul;

  ssl_certificate /etc/certs/artipie-server.crt;
  ssl_certificate_key /etc/certs/artipie-server.key;
  ssl_session_cache shared:SSL:20m;
  ssl_session_timeout 60m;

  location / {
    proxy_pass http://backend-docker;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Authorization $http_authorization;
    proxy_buffering off;
  }
}
```

## Command

```
root@jenkins:~$ docker push docker.artipie.service.consul/test-image:5
The push refers to repository [docker.artipie.service.consul/test-image]
85a60b252f04: Pushing [==================================================>]  18.44MB
6dd85a5520d0: Pushing [==================================================>]  5.632kB
c7986b1e7867: Pushed
f797df612640: Pushed
received unexpected HTTP status: 500 Internal Server Error
```

## Logs

*Posting the logs as replies because of Github's character limit*
