### ISSUE TITLE
credentials.yml may be simplied

### ISSUE THREAD

**Issue by yegor256** [artipie/artipie#203]
Currently, this is the format:

```yaml
credentials:
  jane:
    pass: "plain:qwerty"
  john:
    pass: "sha256:xxxxxxxxxxxxxxxxxxxxxxx"
```

I'm suggesting this:

```yaml
credentials:
  jane:
    type: plain
    pass: qwerty
  john:
    type: sha256
    pass: xxxxxxxxxxxxxxxxxxxxxxx
```
