### ISSUE TITLE
Rpm repository configuration

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#227]
Add settings section for rpm repository configuration: 
```yaml
settings:
  digest: sha256
  naming-policy: sha1
  filelists: true
```
Digest parameter - optional, default sha256, configures `Digest` instance for Rpm: sha256 or sha1.
Naming-policy parameter - optional, default plain, configures `NamingPolicy` for Rpm: plain, sha256 or sha1.
Filelists parameter - optional, default true, includes File Lists for Rpm: true or false.
