### ISSUE TITLE
The credentials section should be optional

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#299]
The credential section in the artipie.yaml file should be optional by default:
```yaml
meta:
  storage:
    type: fs
    path: ./configs
  credentials:
    type: file
    path: _credentials.yaml
  layout: org
  metrics:
    type: log
```

Anyone should be able to do whatever possible by default
