### ISSUE TITLE
Credentials type = file has unclear meanining

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#300]
What is section meaning? What does `type: file` mean? What if there is no file system?

```yaml  
credentials:
    type: file
    path: _credentials.yaml
```
