### ISSUE TITLE
Multi-remote configuration for Docker proxy repository

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#333]
Proposed format for multi-remote proxy configuration of Docker proxy repository:

```yaml
repository:
  type: docker-proxy
  remotes:
    - url: registry-1.docker.io # required
      username: admin # optional
      password: qwerty # optional
      cache: # optional
        storage:
          type: fs
          path: /var/artipie/data
    - url: another-registry.org:54321
```

From: https://github.com/artipie/docker-adapter/issues/160
