### ISSUE TITLE
Backslash in the end of path should be optional

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#344]
Artipie startup command:
```bash
$ docker run --name artipie -it -v $(pwd)/artipie.yaml:/etc/artipie.yml -v $(pwd):/var/artipie -p 8080:80 artipie/artipie:latest
```

Config structure:
```
├── artipie.yaml
├── configs
    └── myhelmrepo.yaml
```

__`myhelmrepo.yaml`__
```yml
repo:
  path: "http://localhost:8080/myhelmrepo"
  type: helm
  storage:
    type: fs
    path: /var/artipie/data
  permissions:
    "*":
      - "*"
```
__`artipie.yaml:`__
```yml
meta:
  storage:
    type: fs
    path: /var/artipie/configs
  layout: flat
```

```bash
$ curl -i  -X POST --data-binary "@tomcat-0.4.1.tgz" http://localhost:8080/myhelmrepo
HTTP/1.1 500 Internal Server Error
Content-Length: 60
transfer-encoding: chunked

Request path /myhelmrepo was not matched to /(?:[^/.]+)(/.*)%
```

```bash
$ curl -i  -X POST --data-binary "@tomcat-0.4.1.tgz" http://localhost:8080/myhelmrepo/
HTTP/1.1 200 OK
transfer-encoding: chunked
```

So I was not able to post a chart until I realized that I need to add a backslash(/) to the end of the path. I think we should allow posting without the backslash in the end.
