### ISSUE TITLE
Support S3 storage in Artipie settings

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#38]
Suggested format:
```
meta:
  storage:
    type: s3
    bucket: my-bucket
    endpoint: https://obs.ap-southeast-3.myhuaweicloud.com
    region: ap-southeast-3
    credentials:
      type: basic
      accessKeyId: ***
      secretAccessKey: ***
```
Only required parameter would be `bucket`, all others may be not specified.
* Default `uri` is amazon URI which is embedded in S3 client
* Default `region` could be taken from environment, see https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/regions/providers/DefaultAwsRegionProviderChain.html
* Default credentials are anonymous
