### ISSUE TITLE
Add emails to users

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#569]
Users in Artipie have only name and password at the moment. It would be nice to also have option to add email for each user. This email (if set) should be configurable via YAML and be supported by HTTP API as well

**Comment by olenagerasimova** [comment]
@olegmoz do I understand correctly, that we are adding `email` field to `credentials.yaml` like this:
```yaml
credentials:
  alena:
    pass: plain:123
    email: alena@artipie.com
```
