### ISSUE TITLE
Readers group support

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#572]
All users added using HTTP API should be automatically added to `readers` group and repositories created using HTTP API should be created with read permissions granted to `readers` group

**Comment by olenagerasimova** [comment]
@olegmoz are we going to implement this by adding `read` permissions for `*` (everyone) in every repository added/updated with HTTP API?

**Comment by olegmoz** [comment]
@olenagerasimova with this approach to revoke read access one will need to make changes in all repositories. That may do the trick as temporary solution, but I think we should actually implement groups. Groups going to be useful for big Artipie installations with many repositories and users

**Comment by olenagerasimova** [comment]
@olegmoz as we discussed, here is my plan:
1. Prepare `http` by changing `Authentication` signature https://github.com/artipie/artipie/issues/573 
2. Release `http` and update it in every adapter (maybe Alexandr can help me here?)
3. Update `http` in artipie and change `AuthFromYaml` to return group list
4. Update rest api clices to add "reader" group to users and repo permissions

Sounds ok?

**Comment by olenagerasimova** [comment]
@olegmoz let's discuss format for save user groups in `credentials.yaml`:
```yaml
credentials:
  artipie:
    pass: plain:artipie
    groups: 
      - reader
      - a-team
      - c-team
  john:
    pass: plain:123
    groups: 
      - reader
      - b-team
``` 
Is this format ok?
