### ISSUE TITLE
Docker images build always fail

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#656]
![image](https://user-images.githubusercontent.com/16746106/94921326-c927e900-04c0-11eb-875b-b50750b7a48b.png)
![image](https://user-images.githubusercontent.com/16746106/94921331-caf1ac80-04c0-11eb-85d7-2abcd4bc01c6.png)

Fail reason: https://github.com/artipie/artipie/runs/1197839942?check_suite_focus=true#step:6:12

```
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

**Comment by Sammers21** [comment]
@olegmoz, hey, can you fix it?

**Comment by olegmoz** [comment]
@Sammers21 that's weird it fails on publishing to `central.artipie.com` on attempt to access `https://registry-1.docker.io/v2/`
@g4s8 do you understand what is going on there?

**Comment by Sammers21** [comment]
@olegmoz, i guess releasing to central artipie should be optional

**Comment by g4s8** [comment]
@olegmoz it seems the workflow has incorrect configuration https://github.com/artipie/artipie/actions/runs/283910426/workflow
```yaml
      - name: Publish Image to Artipie Registry
        uses: elgohr/Publish-Docker-Github-Action@2.19
        with:
          name: central.artipie.com/artipie/docker
          username: ${{ secrets.ARTIPIE_USERNAME }}
          password: ${{ secrets.ARTIPIE_PASSWORD }}
          cache: true
          tags: "latest,${{ env.RELEASE_VERSION }}"
```
it uses default registry host (`registry-1.docker.io`) but it should be `central.artipie.com`, see https://github.com/elgohr/Publish-Docker-Github-Action#registry
