### ISSUE TITLE
RpPermissions.java:34-37: Implement this interface to...

### ISSUE THREAD

**Issue by 0pdd** [artipie/artipie#71]
The puzzle `69-a0681291` from #69 has to be resolved: 

https://github.com/artipie/artipie/blob/dad7bbfb8729068a8ae6b8f3add604b6208ad2ee/src/main/java/com/artipie/RpPermissions.java#L34-L37

The puzzle was created by olenagerasimova on 13-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#71](https://github.com/artipie/artipie/issues/71) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ba02a307-bf14-4279-b1a9-8b834a2a1121); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by olenagerasimova** [comment]
@g4s8 don't toy mind if I change repository yaml configuration structure a little? Embedded sequences for user's permissions do have a lot of sense in our case, so I'd suggest to use mapping and properly escape asterisk:
```
permissions:
  # admin can do everything
  # john can deploy and delete
  # jane can only deploy
  # any user can download
  admin:
    - \*
  john:
    - deploy
    - delete
  jane:
    - deploy
  \*:
    - download
```
