### ISSUE TITLE
Design and describe configuration system

### ISSUE THREAD

**Issue by brastak** [artipie/artipie#78]
Now we have approach then requires multiple config files for every repository. I don't think that this approach is manageable. What's wrong with the idea - every repository defines everything: at this moment at least storage and users. But in the most cases these things should be globally defined. If we have 20 managed repositories, almost all of them will use the same storage (some part of the common storage). If administrator decides to change storage location he must change 20 configs. If administrator is asked to add new user that should have access to the repos, he must change 20 configs.

I think, we need to redesign this approach. One possible solution is to introduce new high-level objects like storages, roles, groups and users (or, maybe, user-provider and group-provider, I don't think that file lists should be the only possible approach) and to allow cross-references between files. But this approach works good only for when we don't need dynamic changes - all config files are read on startup and one global config is created.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@brastak it makes a sense. I think it may be different for users and storages, so I'd discuss only storages in this ticket. What do you think if we reserve some configuration files (e.g. with undercore) for configuring some aliases? E.g. we may have a file `_storages.yaml`:
```yaml
storages:
  # name = "default"
  default:
    type: fs
    path: /var/artipie/maven
  # name = "cloud"
  cloud:
    type: s3
    region: us-east2
    credentials: username/password
```

and reference these aliases from repository configs by name:
```yaml
repo:
  type: maven
  storage: cloud
```
