### ISSUE TITLE
Add the possibility for repositories to have own config properties

### ISSUE THREAD

**Issue by brastak** [artipie/artipie#79]
Extend RepoConfig with method that will return repo-specifig configuration part.
Proposed naming: method custom() that returns YAML node custom. Example:

```
repo:
  type: npm-proxy
  path: npm-proxy
  storage:
    type: fs
    path: /var/artipie/npm-proxy
  custom:
    remote-url: https://registry.npmjs.org
```
