### ISSUE TITLE
Simplified configuration 

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#84]
The minimum artipie configuration, for now, requires 2 files. Which makes it a little painful for a newcomer to get started with the project.

I would propose a single file configuration option: 

```yml
meta:
  storage:
    type: in-place
repo:
  type: rpm
  storage:
    type: fs
    path: /var/artipie/centos
```

This option will definitely make Artipie more user-friendly.
