### ISSUE TITLE
Error "Prefix url for `dist` for uploaded archive was empty" while upload zip to php composer repo

### ISSUE THREAD

**Issue by icukeng** [artipie/artipie#973]
Hello,
I'm trying to upload zipped library to  composer repo with `curl -X PUT -T log-1.1.4.zip  http://localhost:8080/php/` and get this error:
```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Prefix url for `dist` for uploaded archive was empty.
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Prefix url for `dist` for uploaded archive was empty.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.biApply(Unknown Source)
```
Upload  composer.json with `curl -X PUT -T demo1.json  http://localhost:8080/php` works fine.

I`m using docker artipie/artipie:latest with flat layout.
atripie.yml:
```
meta:
  layout: flat
  storage:
    type: fs
    path: /var/artipie/repo
  credentials:
    type: file
    path: _credentials.yml
```
php repo configuration:
```
  path: "/php"
  type: php
  storage:
    type: fs
    path: /var/artipie/data
```
Zip archive is official package (`wget https://github.com/php-fig/log/archive/refs/tags/1.1.4.zip`, then renamed).
