### ISSUE TITLE
Some S3 storage settings should be optional

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#99]
S3 storage configuration requires these settings:
```yaml
repo:
  type: file
  storage:
    type: s3
    region: eu-central-1
    url: s3://artipie.test/binary
    endpoint: https://s3.eu-central-1.amazonaws.com
    bucket: artipie.test
    credentials:
      type: basic
      accessKeyId: <id>
      secretAccessKey: <secret>
```
Default AWS CLI tool requires only access key and secret key (except bucket name), all other parameters should be optional. So this configuration can be working without additional parameters:
```yaml
```yaml
repo:
  type: file
  storage:
    type: s3
    bucket: artipie.test
    credentials:
      type: basic
      accessKeyId: <id>
      secretAccessKey: <secret>
```
```
